shellEmulator: true
shamefullyHoist: true
disallowWorkspaceCycles: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

onlyBuiltDependencies:
  - less
  - sharp
  - workerd
