name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: 签出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: 安装 Node.js 环境
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json

      - name: 安装 Chromium
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: 146

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 安装字体
        run: |
          sudo apt-get update && sudo apt-get install -y fontconfig fonts-noto-cjk

          mkdir -p $HOME/.local/share/fonts/lxgw
          ln -sf $(pwd)/node_modules/@lxgw/LxgwBright/LXGWBright/*.ttf ~/.local/share/fonts/lxgw/

          fc-cache -f -v

          # 调试
          fc-list : family | grep -i "LXGW"

      - name: 构建
        run: pnpm run generate
        env:
          NODE_ENV: production

      - name: 部署到 Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy ./dist --project-name=sharpicehome
